import http from "node:http";
import {readFileSync,existsSync} from "node:fs";
import {WebSocket,WebSocketServer} from "ws";

if(existsSync(".env.local"))for(const line of readFileSync(".env.local","utf8").split(/\r?\n/)){const i=line.indexOf("=");if(i>0&&!line.startsWith("#")){const key=line.slice(0,i).trim(),value=line.slice(i+1).trim();if(!process.env[key])process.env[key]=value}}

const PORT=Number(process.env.PORT||8080);
const TWELVE_DATA_API_KEY=process.env.TWELVE_DATA_API_KEY;
if(!TWELVE_DATA_API_KEY)throw new Error("TWELVE_DATA_API_KEY must be set in .env.local or the hosting environment.");

const COINBASE_URL="wss://advanced-trade-ws.coinbase.com";
const TWELVE_URL=`wss://ws.twelvedata.com/v1/quotes/price?apikey=${encodeURIComponent(TWELVE_DATA_API_KEY)}`;
const CRYPTO_SYMBOLS=["BTC-USD","ETH-USD"];
const MULTI_ASSET_SYMBOLS=["AAPL","NVDA","EUR/USD"];
const latest=new Map();
const sourceState={coinbase:{status:"starting",lastMessage:0},twelveData:{status:"starting",lastMessage:0}};
const clients=new Set();

function json(res,status,body){res.writeHead(status,{"Content-Type":"application/json","Access-Control-Allow-Origin":"*","Cache-Control":"no-store"});res.end(JSON.stringify(body))}
function broadcast(message){const payload=JSON.stringify(message);for(const client of clients)if(client.readyState===WebSocket.OPEN)client.send(payload)}
function publish(tick){if(!Number.isFinite(tick.price))return;const normalized={type:"tick",...tick,timestamp:tick.timestamp||new Date().toISOString()};latest.set(normalized.symbol,normalized);broadcast(normalized)}
function reconnectingSocket(name,connect){let socket,timer,attempt=0,stopped=false;const start=()=>{if(stopped)return;sourceState[name].status="connecting";socket=connect({onOpen(){attempt=0;sourceState[name].status="live"},onMessage(){sourceState[name].lastMessage=Date.now();sourceState[name].status="live"},onClose(){if(stopped)return;sourceState[name].status="reconnecting";const delay=Math.min(30000,1000*2**attempt++)+Math.floor(Math.random()*500);timer=setTimeout(start,delay)}})};start();return()=>{stopped=true;clearTimeout(timer);socket?.close()}}

function startCoinbase(){return reconnectingSocket("coinbase",hooks=>{const ws=new WebSocket(COINBASE_URL);ws.on("open",()=>{hooks.onOpen();ws.send(JSON.stringify({type:"subscribe",product_ids:CRYPTO_SYMBOLS,channel:"ticker"}));ws.send(JSON.stringify({type:"subscribe",channel:"heartbeats"}))});ws.on("message",raw=>{hooks.onMessage();try{const message=JSON.parse(raw.toString());for(const event of message.events||[])for(const ticker of event.tickers||[])publish({source:"coinbase",assetClass:"crypto",symbol:ticker.product_id,price:Number(ticker.price),volume24h:Number(ticker.volume_24_h),change24h:Number(ticker.price_percent_chg_24_h),high24h:Number(ticker.high_24_h),low24h:Number(ticker.low_24_h),timestamp:message.timestamp})}catch(error){console.error("Coinbase message error",error.message)}});ws.on("close",hooks.onClose);ws.on("error",error=>{console.error("Coinbase connection error",error.message);ws.close()});return ws})}

function startTwelveData(){let heartbeat;const stop=reconnectingSocket("twelveData",hooks=>{const ws=new WebSocket(TWELVE_URL);ws.on("open",()=>{hooks.onOpen();ws.send(JSON.stringify({action:"subscribe",params:{symbols:MULTI_ASSET_SYMBOLS.join(",")}}));heartbeat=setInterval(()=>{if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify({action:"heartbeat"}))},10000)});ws.on("message",raw=>{hooks.onMessage();try{const message=JSON.parse(raw.toString());if(message.event==="price")publish({source:"twelveData",assetClass:message.symbol.includes("/")?"forex":"stock",symbol:message.symbol,price:Number(message.price),timestamp:message.timestamp?new Date(Number(message.timestamp)*1000).toISOString():new Date().toISOString()});else if(message.status==="error")console.error("Twelve Data subscription error",message.message)}catch(error){console.error("Twelve Data message error",error.message)}});ws.on("close",()=>{clearInterval(heartbeat);hooks.onClose()});ws.on("error",error=>{console.error("Twelve Data connection error",error.message);ws.close()});return ws});return()=>{clearInterval(heartbeat);stop()}}
async function pollMultiAsset(){for(const symbol of MULTI_ASSET_SYMBOLS)try{const response=await fetch(`https://api.twelvedata.com/price?symbol=${encodeURIComponent(symbol)}`,{headers:{Authorization:`apikey ${TWELVE_DATA_API_KEY}`,Accept:"application/json"}});const data=await response.json();const price=Number(data.price);if(Number.isFinite(price))publish({source:"twelveData",assetClass:symbol.includes("/")?"forex":"stock",symbol,price,timestamp:new Date().toISOString()})}catch(error){console.error(`Twelve Data REST error for ${symbol}`,error.message)}}

function research(symbol){const tick=latest.get(symbol);if(!tick)return{error:`No live price has arrived for ${symbol} yet.`,generatedAt:new Date().toISOString()};const change=Number(tick.change24h||0),bullish=change>=0,entry=tick.price*(bullish?.997:1.003),stop=tick.price*(bullish?.978:1.022),target=tick.price*(bullish?1.025:.975);return{symbol,generatedAt:new Date().toISOString(),source:tick.source,sourceTimestamp:tick.timestamp,signal:bullish?"Cautious long":"Wait / defensive",confidence:Math.min(86,Math.round(58+Math.abs(change)*4)),evidence:[`Live ${tick.source} price: ${tick.price}`,`24-hour change: ${change.toFixed(2)}%`,tick.volume24h?`24-hour volume: ${tick.volume24h}`:"Latest provider tick received"],paperTradePlan:{side:bullish?"buy":"sell",entry:Number(entry.toFixed(6)),stop:Number(stop.toFixed(6)),target:Number(target.toFixed(6)),maxPositionPercent:0.25},disclaimer:"Research simulation only. This does not place an order."}}
async function candleHistory(symbol){if(symbol.includes("-")){const r=await fetch(`https://api.exchange.coinbase.com/products/${encodeURIComponent(symbol)}/candles?granularity=60`);if(!r.ok)throw new Error("Coinbase candles unavailable");const data=await r.json();return data.slice(0,200).reverse().map(x=>({time:x[0],low:Number(x[1]),high:Number(x[2]),open:Number(x[3]),close:Number(x[4])}))}const r=await fetch(`https://api.twelvedata.com/time_series?symbol=${encodeURIComponent(symbol)}&interval=1min&outputsize=200`,{headers:{Authorization:`apikey ${TWELVE_DATA_API_KEY}`,Accept:"application/json"}});if(!r.ok)throw new Error("Twelve Data candles unavailable");const data=await r.json();if(!data.values)throw new Error(data.message||"No candle history");return data.values.reverse().map(x=>({time:Math.floor(new Date(x.datetime+"Z").getTime()/1000),open:Number(x.open),high:Number(x.high),low:Number(x.low),close:Number(x.close)}))}

const server=http.createServer(async(req,res)=>{const url=new URL(req.url||"/",`http://${req.headers.host||"localhost"}`);if(req.method==="OPTIONS"){res.writeHead(204,{"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,OPTIONS","Access-Control-Allow-Headers":"Content-Type"});return res.end()}if(url.pathname==="/"){res.writeHead(200,{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store"});return res.end(readFileSync("index.html"))}if(url.pathname==="/health")return json(res,200,{ok:true,sources:sourceState,symbols:[...latest.keys()],serverTime:new Date().toISOString()});if(url.pathname==="/api/latest")return json(res,200,{data:Object.fromEntries(latest),sources:sourceState});if(url.pathname==="/api/research")return json(res,200,research(url.searchParams.get("symbol")||"BTC-USD"));if(url.pathname==="/api/candles")try{return json(res,200,{symbol:url.searchParams.get("symbol")||"BTC-USD",candles:await candleHistory(url.searchParams.get("symbol")||"BTC-USD")})}catch(error){return json(res,503,{error:error.message})}return json(res,404,{error:"Not found"})});
const gateway=new WebSocketServer({server});gateway.on("connection",client=>{clients.add(client);client.send(JSON.stringify({type:"snapshot",data:Object.fromEntries(latest),sources:sourceState,timestamp:new Date().toISOString()}));client.on("close",()=>clients.delete(client));client.on("error",()=>clients.delete(client))});

const stopCoinbase=startCoinbase(),stopTwelve=startTwelveData();
pollMultiAsset();const restPoll=setInterval(pollMultiAsset,10000);
const staleMonitor=setInterval(()=>{const now=Date.now();for(const [name,state] of Object.entries(sourceState))if(state.lastMessage&&now-state.lastMessage>30000){state.status="stale";broadcast({type:"source-status",source:name,status:"stale",timestamp:new Date().toISOString()})}},5000);
server.listen(PORT,()=>console.log(`Arc market gateway listening on http://localhost:${PORT}`));
function shutdown(){clearInterval(staleMonitor);clearInterval(restPoll);stopCoinbase();stopTwelve();gateway.close();server.close(()=>process.exit(0))}process.on("SIGINT",shutdown);process.on("SIGTERM",shutdown);
