"use client";
import {useEffect,useMemo,useState} from "react";
type Asset={symbol:string;name:string;group:string;price:number;previous:number;updated:number;source:string};
const seed=[{symbol:"BTC-USD",name:"Bitcoin",group:"Cryptocurrency"},{symbol:"ETH-USD",name:"Ethereum",group:"Cryptocurrency"},{symbol:"AAPL",name:"Apple",group:"Stocks"},{symbol:"NVDA",name:"NVIDIA",group:"Stocks"},{symbol:"SPY",name:"S&P 500 ETF",group:"Stocks"},{symbol:"QQQ",name:"Nasdaq 100 ETF",group:"Stocks"},{symbol:"EUR/USD",name:"Euro / US Dollar",group:"Forex"}];
export default function Live(){const [assets,setAssets]=useState<Asset[]>(seed.map(x=>({...x,price:0,previous:0,updated:0,source:"Waiting"}))),[chosen,setChosen]=useState("BTC-USD"),[research,setResearch]=useState<any>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 useEffect(()=>{let alive=true;async function refresh(){const data=await Promise.all(seed.map(async x=>{try{const r=await fetch(`/api/market?symbol=${encodeURIComponent(x.symbol)}`,{cache:"no-store"});return r.ok?await r.json():null}catch{return null}}));if(alive)setAssets(old=>old.map(a=>{const d=data.find(x=>x?.symbol===a.symbol);return d?{...a,previous:a.price||d.price,price:d.price,updated:Date.now(),source:d.provider||(a.symbol.endsWith("-USD")?"Live exchange feed":"Twelve Data")}:a}))}refresh();const id=setInterval(refresh,5000);return()=>{alive=false;clearInterval(id)}},[]);
 useEffect(()=>{let ws:WebSocket|undefined,closed=false,retry=1000;const connect=()=>{if(closed)return;ws=new WebSocket("wss://advanced-trade-ws.coinbase.com");ws.onopen=()=>{retry=1000;ws?.send(JSON.stringify({type:"subscribe",product_ids:["BTC-USD","ETH-USD"],channel:"ticker"}));ws?.send(JSON.stringify({type:"subscribe",channel:"heartbeats"}))};ws.onmessage=e=>{try{const d=JSON.parse(e.data);for(const ev of d.events||[])for(const t of ev.tickers||[])setAssets(old=>old.map(a=>a.symbol===t.product_id?{...a,previous:a.price||Number(t.price),price:Number(t.price),updated:Date.now(),source:"Live exchange feed"}:a))}catch{}};ws.onclose=()=>{if(!closed)setTimeout(connect,retry);retry=Math.min(30000,retry*2)}};connect();return()=>{closed=true;ws?.close()}},[]);
 async function run(){setBusy(true);setNotice("");try{const r=await fetch(`/api/research?symbol=${encodeURIComponent(chosen)}`,{cache:"no-store"});setResearch(await r.json())}finally{setBusy(false)}}
 const groups=useMemo(()=>["Cryptocurrency","Stocks","Forex"],[]);return <div className="livepage"><header><a href="/">A</a><b>ARC UNIFIED FEED</b><span>PAPER TRADING ONLY</span><a href="/">← Full platform</a></header><main><section className="liveassets"><h1>All markets, one feed</h1><p>Live crypto streaming with Twelve Data equities and foreign exchange.</p>{groups.map(g=><section className="livegroup" key={g}><h2>{g}</h2><div className="livetable"><div><span>Asset</span><span>Last price</span><span>Source</span><span>Status</span></div>{assets.filter(a=>a.group===g).map(a=>{const age=Date.now()-a.updated,status=!a.updated||age>15000?"OFFLINE":age>5000?"STALE":"LIVE";return <button key={a.symbol} onClick={()=>setChosen(a.symbol)}><span><i>{a.symbol.split(/[-/]/)[0]}</i><b>{a.symbol}</b><small>{a.name}</small></span><strong className={a.price>a.previous?"flashup":a.price<a.previous?"flashdown":""}>{a.price?money(a.price):"—"}</strong><span>{a.source}</span><em className={status.toLowerCase()}>{status}</em></button>})}</div></section>)}</section><aside className="researchhub"><small>AGENT RESEARCH COMMAND</small><h2>Evidence before action</h2><select value={chosen} onChange={e=>setChosen(e.target.value)}>{assets.map(a=><option key={a.symbol}>{a.symbol}</option>)}</select><button onClick={run} disabled={busy}>{busy?"Researching…":"Run research"}</button>{research?.evidence?<article><b>{research.symbol} · {research.signal}</b><time>{new Date(research.generatedAt).toLocaleString()}</time><ul>{research.evidence.map((x:string)=><li key={x}>{x}</li>)}</ul><div><span>Entry<b>{money(research.entry)}</b></span><span>Stop<b>{money(research.stop)}</b></span><span>Target<b>{money(research.target)}</b></span><span>Confidence<b>{research.confidence}%</b></span></div></article>:<p>Select an asset and run a fresh timestamped scan.</p>}<div className="decisions"><button disabled={!research?.evidence} onClick={()=>setNotice("Paper plan approved. No live order was sent.")}>Approve paper plan</button><button disabled={!research?.evidence} onClick={()=>{setResearch(null);setNotice("Plan rejected.")}}>Reject</button></div>{notice&&<strong className="agentnotice">{notice}</strong>}</aside></main></div>}
function money(v:number){return Number.isFinite(v)?v.toLocaleString(undefined,{style:"currency",currency:"USD",minimumFractionDigits:v<1?5:2,maximumFractionDigits:v<1?5:2}):"—"}
